services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cortex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/cortex
      QDRANT_URL: http://qdrant:6333
      JWT_SECRET: ${JWT_SECRET:-cortex_super_secret_jwt_key_2026}
      GROQ_API_KEY: ${GROQ_API_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_HOST: ${LANGFUSE_HOST:-http://langfuse:3000}
      CORS_ORIGINS: '["http://localhost:3000"]'
    volumes:
      # Live codebase mounting for instant hot-reloading
      - ./backend:/app/backend
      - ./tests:/app/tests
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      WATCHPACK_POLLING: "true" # Ensures hot reloading on Mac/Linux file mounts
    volumes:
      # Live codebase mounting for instant UI hot-reloading
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  langfuse:
    image: langfuse/langfuse:2
    ports:
      - "3030:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/langfuse
      NEXTAUTH_SECRET: dkhfdfjgdflgjdsfklgjsdljgsdljglfhglsfdg
      NEXTAUTH_URL: http://localhost:3030
      SALT: kdjhfdhfldgkdhldfdlglkgfg
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  qdrantdata:
